baseURL = "https://charmixer.dev/"
title = "Charmixer"
languageCode = "en-us"
theme = "m10c"

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[[params.social]]
  name = "github"
  url = "https://github.com/charmixer"

[params]
  author = "Charmixer"
  description = "A place for my thoughts"
  avatar = "/img/charmixer.jpg"

[params.style]
  darkestColor = "#073642"
  darkColor = "#002b36"
  lightColor = "#839496"
  lightestColor = "#eee8d5"
  primaryColor = "#268bd2"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 2
